/**
 ******************************************************************************
 * @file           : gpio_toggle.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <string.h>
#include "stm32f411xx.h"
#include "stm32f411xx_gpio_driver.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
  GPIO_Handle_t builtinLEDGpio;
  builtinLEDGpio.pGPIOx = GPIOC;
  builtinLEDGpio.GPIO_PinConfig.GPIO_PinMode=GPIO_MODE_OUTPUT;
  builtinLEDGpio.GPIO_PinConfig.GPIO_PinNumber=GPIO_PIN_13;
  builtinLEDGpio.GPIO_PinConfig.GPIO_PinOPType=GPIO_OP_TYPE_OD;
  builtinLEDGpio.GPIO_PinConfig.GPIO_PinPuPdControl=GPIO_PIN_NO_PUPD;
  builtinLEDGpio.GPIO_PinConfig.GPIO_PinSpeed=GPIO_OP_SPEED_HI;

  GPIO_PClockControl(GPIOC, ENABLE);
  GPIO_Init(&builtinLEDGpio);

  /* Loop forever */
	for(;;){
      GPIO_ToggleOutputPin(GPIOC,GPIO_PIN_13);
      for(uint32_t i=0; i<200000; i++);
  }
}
